### PR TITLE
Merge development branch to master

### PR DESCRIPTION
**Pull request by ladybugbot**

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, I'm curious to see what will happen when you merge this in. The `__version__` in dev branch is behind the one in master branch. I think we should have synced the development branch after semantic release which changes the `__version__` in `__init__` file.

I'm actually thinking that we may want to change that manually right now to avoid any issues.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Ok, I can update the `__version__`. Then I will approve it and you can merge it in.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Once  you approve [this PR](https://github.com/ladybug-tools/ladybug/pull/124), I will approve this one and it should be ready to merge.

**Comment by chriswmackey** [comment]
All set, @mostaphaRoudsari . You can do the honors of merging it in!

**Pull request merged**
