### PR TITLE
perf(dict): Replacing to_json() and from_json() with to_dict() and from_dict()

### PR DESCRIPTION
**Pull request by chriswmackey**
I figured that it was best to cluster the perf-type edits to ladybug core together since we are already making them in regards to the [ladybug_geometry switch](https://github.com/ladybug-tools/ladybug/pull/141).  So I have done the conversion of to/from_json over to to/from_dict.  I also replaced the `hasattr` calls with `isinstance` given that we are generally trying to make the core correct now without worrying about limitations of Dyanmo.  I will create a PR for the ladybug[+] and honeybee[+] grasshopper components that accommodates with these changes.

### CODE REVIEW

**Comment by AntoineDao** [comment]
Oh hi! Going to be difficult again but you probably want to remove all commits from #141 from this PR otherwise you're going to have conflicts once you merge one or the other of these branches.

**Comment by mostaphaRoudsari** [comment]
IMO rhe best way to do this is to keep the new changes in your fork for now and don't send a PR. Then once the previous PR is merged do the update in your branch and send a new PR.

 Here is an example: https://github.com/ladybug-tools/honeybee-radiance/network

Once the changes from master is merged I will rebase and merge in the changes from material to master and send a new PR.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @AntoineDao ,

I should have said this in the PR description but the plan was to close this PR and deal with these changes only after the geometry PR is merged (I know that this commit history is too messy to merge here).  The main reason I sent the PR was just to let you know that this switch from `to_json` over to `to_dict` is ready fir Ladybug since, as you said, we should make this change across all of the repos together. Actually, now that I think about it, I could have just done a draft PR so I'll do that in the future. In any case, now that you are aware, let me know if you just want me to close this one out.

**Comment by AntoineDao** [comment]
lol no worries and no pressure 😄 Do as you guys see fit. Just thought I'd flag potential issues before we start battling to clean up commit spaghetti!

**Comment by mostaphaRoudsari** [comment]
Let's do this right after merging the other one. It will be useful to make the change sooner than later and since it is really a find and replace I'm not sure if it even needs a review.

**Comment by AntoineDao** [comment]
Unless you've got tests setup for it and they fail 😛

**Comment by chriswmackey** [comment]
All sounds good. I will close this now and we'll make a new one afterwards.

**Pull request closed without merging**
