### PR TITLE
Added '__slots__'

### PR DESCRIPTION
**Pull request by mkrueger12**
Add `__slots__` to epw.py

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Also I just check the tests and you are at least missing `_matadata`. You can see it for yourself here: https://travis-ci.org/github/ladybug-tools/ladybug/jobs/682683655

**Comment by mkrueger12** [comment]
I have updated the file and corrected the syntax. Do I submit a new PR?

**Comment by mostaphaRoudsari** [comment]
Thanks. You don't need to send a new PR. Every new commit to your `master` branch will update this PR automatically.

Thank you for the changes! The tests are still failing. You can run the tests locally using ` pytest ./tests` too. 😀

I see that you have also changed a number of dependencies in the file. Is that intentional? I don't think we need to change the imports for adding `__slots__`.

**Comment by mkrueger12** [comment]
Sounds good. I will run the test locally. This is my first time doing this so thanks for the help. I'm not sure what may have caused the dependency sorting but it was unintentional.

**Comment by mostaphaRoudsari** [comment]
> This is my first time doing this so thanks for the help.

I figured. no worries. We all started one day and went through a similar process. Let me know if you have any other questions. Will be happy to help. 😀

> I will run the test locally.

Sounds good. If you haven't already you may want to install the dependencies using `pip install -r dev-requirements.txt`

> I'm not sure what may have caused the dependency sorting but it was unintentional.

You might have an extension installed on your editor that does it for you on save.

**Comment by mkrueger12** [comment]
epw_test.py runs without error locally. Thoughts?

**Comment by mostaphaRoudsari** [comment]
Thank you @mkrueger12! Well done. The tests are passing. I added @chriswmackey to have another look and make the final call.

**Pull request merged**
