### PR TITLE
refactor(dict): Add type key to to_dict() of ladybug core objects

### LINKED ISSUE #157: Add the `type` key to all dictionary versions of ladybug-core objects
We realized while working on honeybee that it is very helpful to have a `type` key in the dictionary that is output by `to_dict`, which contains the name of the object class.  For example, a dictionary for AnalysisPeriod should look like:
```
{"type: "AnalysisPeriod",
"from_month": 1,
"from_day": 1,
"from_hour": 0,
"to_month": 12,
"to_day": 21,
"to_hour": 23}
```
We need to go through all of the `to_dict` methods in the library and add the `type` key.  If anyone wants to take this up, please feel free.  Otherwise, I will get to it within a few months.

### PR DESCRIPTION
**Pull request by polandar**
resolves #157 

This is my first time contributing, so please feel free to explain any obvious things I am missing in the codebase/CI setup

### CODE REVIEW

**Comment by chriswmackey** [comment]
This looks great, @polandar .  Thank you for addressing this and this is exactly what we wanted.

My only question is whether we should also add a line in each of the `from_dict` methods that checks the type key.  For example, for `AnalysisPeriod.from_dict()`, we might want to have the first line of code be:
```
assert data['type'] == 'AnalysisPeriod', 'Expected AnalysisPeriod dictionary. Got {}.'.format(data['type'])
```
@mostaphaRoudsari , what you do think about this?  I know that having a check like this helped me quickly identify some places where I was sending an incorrect dictionary in the past. We can also address this in a future PR, @polandar , so there's no need to add it until we get confirmation from Mostapha.
Thanks again!

**Comment by polandar** [comment]
I am happy to wait for a resolution either way @chriswmackey

**Comment by chriswmackey** [comment]
@polandar ,

Once you confirm that you are signed up for Hacktoberfest, we can merge it in. 

If you are able to address @mostaphaRoudsari 's note about the double quotes in this PR, that would also be nice. You should be able to do this by just making the edits on your end and pushing another commit.

We'll agree to address the `from_dict` type check in a later PR.

**Comment by polandar** [comment]
@chriswmackey 
Hi, yes, I have signed up but this won't count against my quota cos I've got 4+ PRs in already.

Happy to do the quotes (within 36hrs if that's ok) and will ping you on here when done

**Comment by polandar** [comment]
> @chriswmackey
> Hi, yes, I have signed up but this won't count against my quota cos I've got 4+ PRs in already.
> 
> Happy to do the quotes (within 36hrs if that's ok) and will ping you on here when done

And all done

**Comment by mostaphaRoudsari** [comment]
Done! Thank you @polandar!

**Comment by lauleh** [comment]
Good evening @polandar,
My name is Lauleh and I am reaching out from Ladybug Tools.
I want to personally thank you for making contributions to our repositories during the Hacktoberfest 2019.
If you can kindly take a moment to e-mail me (lauleh@ladybug.tools) your mailing address, I would like to send you a Ladybug Tools sticker. Thank you so much!

Best,

-- 
Lauleh Aslani | Administrative Assistant 
Ladybug Tools
www.ladybug.tools | lauleh@ladybug.tools

**Pull request merged**
